# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-Shm-Simple
version:      1.00
version_from: Simple.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Attrib:                 0
    DynaLoader:                    0
    Fcntl:                         0
    IPC::SysV:                     0
    UNIVERSAL:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
