--- linux/usr/Makefile.orig	2017-11-10 17:59:16.796093778 -0500
+++ linux/usr/Makefile	2017-11-10 18:03:23.153078209 -0500
@@ -24,7 +24,10 @@
 hostprogs-y := gen_init_cpio
 initramfs   := $(CONFIG_SHELL) $(srctree)/scripts/gen_initramfs_list.sh
 ramfs-input := $(if $(filter-out "",$(CONFIG_INITRAMFS_SOURCE)), \
-			$(shell echo $(CONFIG_INITRAMFS_SOURCE)),-d)
+			$(shell echo $(CONFIG_INITRAMFS_SOURCE)),-d) \
+               $(if $(filter-out "",$(CONFIG_INITRAMFS_HELPER)), \
+			$(shell echo $(CONFIG_INITRAMFS_HELPER)),-d)
+
 ramfs-args  := \
         $(if $(CONFIG_INITRAMFS_ROOT_UID), -u $(CONFIG_INITRAMFS_ROOT_UID)) \
         $(if $(CONFIG_INITRAMFS_ROOT_GID), -g $(CONFIG_INITRAMFS_ROOT_GID))
